
--TẠO BẢNG
CREATE TABLE SINHVIEN
(
    MSSV varchar2(12) NOT NULL,
    HOTENSV nvarchar2(50),
    NGAYSINH date,
    GIOITINH nvarchar2(10),
    DIACHI nvarchar2(100),
    LOP nvarchar2(20),
    TINHTRANG nvarchar2(30)
)

create table TAIKHOAN
(
    ID varchar2(12) not null,
    MATKHAU nvarchar2(50)
)

create table GIAOVIEN
(
    MSGV varchar(12),
    HOTENGV nvarchar2(50),
    NGAYSINH date,
    GIOITINH nvarchar2(10),
    MAMONHOC VARCHAR2(12)
)

create table MONHOC
(
    MAMONHOC varchar2(12),
    TENMONHOC nvarchar2(50),
    SOCHI int
)

create table DETHI
(
    MADETHI varchar2(12),
    MAMONHOC varchar2(12),
    MACAUHOI varchar2(12),
    THOIGIAN_BATDAU TIMESTAMP, --TIMESTAMP LƯU TRỮ THÔNG TIN GIỜ&NGÀY THÁNG NĂM
    SOCAUHOI int
)

create table CAUHOI
(
    MAMONHOC varchar2(12),
    MACAUHOI varchar2(12),
    CAUHOI NVARCHAR2(1000),
    DAPANA nvarchar2(500),
    DAPANB nvarchar2(500),
    DAPANC nvarchar2(500),
    DAPAND nvarchar2(500),
    DAPAN_DUNG nvarchar2(100)
) 

create table KETQUA
(
    MSSV varchar(12),
    MAMONHOC varchar2(12),
    MADETHI varchar2(12),
    DIEMTHI float,
    THOIGIAN_HOANTHANH TIMESTAMP
)


---TẠO KHÓA CHÍNH
ALTER TABLE SINHVIEN
ADD CONSTRAINT PK_SINHVIEN PRIMARY KEY (MSSV)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MSGV)

ALTER TABLE TAIKHOAN
ADD CONSTRAINT PK_TAIKHOAN PRIMARY KEY (ID)

ALTER TABLE MONHOC
ADD CONSTRAINT PK_MONHOC PRIMARY KEY (MAMONHOC)

ALTER TABLE DETHI
ADD CONSTRAINT PK_DETHI PRIMARY KEY (MADETHI,MAMONHOC)

ALTER TABLE CAUHOI
ADD CONSTRAINT PK_CAUHOI PRIMARY KEY (MACAUHOI,MAMONHOC)

ALTER TABLE KETQUA
ADD CONSTRAINT PK_KETQUA PRIMARY KEY (MSSV,MADETHI,MAMONHOC)

---TẠO KHÓA NGOẠI
ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN FOREIGN KEY (MSSV) REFERENCES TAIKHOAN(ID);

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN FOREIGN KEY (MSGV) REFERENCES TAIKHOAN(ID);

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_MAMH FOREIGN KEY (MAMONHOC) REFERENCES MONHOC(MAMONHOC);

ALTER TABLE CAUHOI
ADD CONSTRAINT FK_CAUHOI_MAMH FOREIGN KEY (MAMONHOC) REFERENCES MONHOC(MAMONHOC);

ALTER TABLE DETHI
ADD CONSTRAINT FK_DETHI_MONHOC FOREIGN KEY (MAMONHOC) REFERENCES MONHOC(MAMONHOC)

ALTER TABLE KETQUA 
ADD CONSTRAINT FK_KETQUA_SINHVIEN FOREIGN KEY (MSSV)  REFERENCES SINHVIEN(MSSV);

ALTER TABLE KETQUA 
ADD  CONSTRAINT FK_KETQUA_MONHOC FOREIGN KEY (MAMONHOC) REFERENCES MONHOC(MAMONHOC);

--ALTER TABLE KETQUA
--ADD  CONSTRAINT FK_KETQUA_DETHI FOREIGN KEY (MADETHI) REFERENCES DETHI(MADETHI);


-----------------------------NHẬP LIỆU
 
-- truoc khi nhap lieu phai cap quota tren tablespace (luu y chay tren user sys)
alter user CauHoiTracNghiem quota 100M on users;

alter session set NLS_DATE_FORMAT = 'DD-MM-YYYY';

---NHẬP LIỆU CHO BẢNG TÀI KHOẢN TRƯỚC
INSERT INTO TAIKHOAN (ID,MATKHAU) VALUES ('HV00001','123');
INSERT INTO TAIKHOAN (ID,MATKHAU) VALUES ('HV00002','123');
INSERT INTO TAIKHOAN (ID,MATKHAU) VALUES ('GV0009','123');
INSERT INTO TAIKHOAN (ID,MATKHAU) VALUES ('GV0010','123');


INSERT INTO SINHVIEN (MSSV, HOTENSV, NGAYSINH, GIOITINH, TINHTRANG,DIACHI, LOP)
values ('HV00001',N' Nguyễn Thị Thùy Trang', '01-02-1992',N'Nữ', N'Buộc thôi học',NULL, NULL);
INSERT INTO SINHVIEN (MSSV, HOTENSV, NGAYSINH, GIOITINH, TINHTRANG,DIACHI, LOP)
values ('HV00002',N' Nguyễn Thị Trâm Anh', '01-02-1992',N'Nữ', N'Buộc thôi học',NULL, NULL);

insert into GIAOVIEN (MSGV,hotengv,NGAYSINH, GIOITINH, MAMONHOC)
values ('GV0009', N'Trần Thị Kiều', '03-01-1984', N'Nữ', null);
insert into GiaoVien (MSGV,hotengv,NGAYSINH, GIOITINH, MAMONHOC)
values ('GV0010', N'Trần Phương Loan', '30-4-1982', N'Nữ', null);

---MÃ HÓA DATABASE BẰNG AES

--YÊU CẦU CẤP QUYỀN
GRANT EXECUTE ON DBMS_CRYPTO TO CauHoiTracNghiem;
GRANT CREATE PROCEDURE TO CauHoiTracNghiem;


CREATE OR REPLACE FUNCTION f_encryptData(p_data nvarchar2)
RETURN RAW IS
    encryptedData RAW(20000);
    l_key RAW(32) := UTL_RAW.CAST_TO_RAW('12345678901234567890123456789012'); 
    l_iv  RAW(16) := UTL_RAW.CAST_TO_RAW('1234567890123456');
BEGIN
    encryptedData := DBMS_CRYPTO.ENCRYPT(
        src => UTL_RAW.CAST_TO_RAW(p_data), 
        typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5, 
        key => l_key,
        iv  => l_iv);
    RETURN encryptedData;
END;

--GIẢI MÃ DATABASE BẰNG AES
CREATE OR REPLACE FUNCTION f_decryptData(encryptedData RAW)
RETURN NVARCHAR2 IS
    decryptedData NVARCHAR2(20000);
    l_key RAW(32) := UTL_RAW.CAST_TO_RAW('12345678901234567890123456789012');
    l_iv  RAW(16) := UTL_RAW.CAST_TO_RAW('1234567890123456');
BEGIN
    -- Giải mã dữ liệu đã mã hóa
    decryptedData := UTL_RAW.CAST_TO_NVARCHAR2(DBMS_CRYPTO.DECRYPT(
        src => encryptedData, 
        typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5, 
        key => l_key,
        iv  => l_iv));
    RETURN decryptedData;
END;

--- TEST HÀM MÃ HÓA & GIẢI MÃ
SELECT ID, f_encryptData(MATKHAU) AS MATKHAU FROM TAIKHOAN;
SELECT * FROM TAIKHOAN;
UPDATE TAIKHOAN SET MATKHAU = f_encryptData(MATKHAU);


--thêm dữ liệu vào bảng bằng cách thêm hàm encrypt vào lệnh INSERT
INSERT INTO TAIKHOAN(ID, MATKHAU) VALUES('HV00003',f_encryptData('123'));
SELECT ID, f_decryptData(MATKHAU) AS MATKHAU FROM TAIKHOAN;

delete
from taikhoan
where id = 'HV00003'

DROP TABLE TAIKHOAN
DROP TABLE GIAOVIEN
DROP TABLE SINHVIEN
DROP TABLE KETQUA
DROP TABLE MONHOC
DROP TABLE DETHI
DROP TABLE CAUHOI