alter session set "_ORACLE_SCRIPT"=true; 

create user CauHoiTracNghiem identified by 123

grant create session to CauHoiTracNghiem

grant create table to CauHoiTracNghiem

alter user CauHoiTracNghiem quota 100M on users

GRANT CREATE USER TO cauhoitracnghiem;
GRANT ALTER USER TO cauhoitracnghiem;
GRANT GRANT ANY PRIVILEGE TO cauhoitracnghiem;
GRANT SELECT ON SYS.DBA_USERS TO CauHoiTracNghiem;
GRANT SELECT ON SYS.DBA_PROFILES TO CauHoiTracNghiem;
GRANT CREATE PROFILE TO CauHoiTracNghiem;
GRANT CREATE ROLE TO CauHoiTracNghiem;
GRANT GRANT ANY PRIVILEGE TO CauHoiTracNghiem;


create user GV0001 identified by 123
grant create session to GV0001
alter user GV0001 PROFILE HocSinh
GRANT DATAENTRY_GiaoVien TO GV0001

----------ghi nhật ký và giải trình sử dụng Standard Auditing, trigger
---chạy sys:
grant create sequence to CauHoiTracNghiem;

CREATE SEQUENCE seq_audit_log
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE audit_log(
    logID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actionTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
    ID VARCHAR2(12), --HOC SINH HOAC GIAO VIEN
    actionType VARCHAR2(50), --INSERT, UPDATE, DELETE
    tableName VARCHAR2(50),
    details NVARCHAR2(2000)
)

DROP TABLE audit_log


CREATE OR REPLACE TRIGGER trg_questions_audit
AFTER INSERT OR UPDATE OR DELETE ON CAUHOI
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO audit_log ( ID, actionType, tableName, details)
        VALUES (USER, 'INSERT', 'CAUHOI', N'Đã thêm câu hỏi: ' || :NEW.CAUHOI);
    ELSIF UPDATING THEN
        INSERT INTO audit_log (ID, actionType, tableName, details)
        VALUES (USER, 'UPDATE', 'CAUHOI',
               N'Cập nhật câu hỏi từ: ' || :OLD.CAUHOI || N' thành: ' || :NEW.CAUHOI);
    ELSIF DELETING THEN
        INSERT INTO audit_log (ID, actionType, tableName, details)
        VALUES (USER, 'DELETE', 'CAUHOI', N'Đã xóa câu hỏi: ' || :OLD.CAUHOI);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_student_answers_audit
AFTER INSERT ON KETQUA
FOR EACH ROW
BEGIN
    INSERT INTO audit_log (ID, actionType, tableName, details)
    VALUES (:NEW.MSHS, 'INSERT', 'KETQUA',
            N'Đã nộp bài ' || :NEW.MAMONHOC || N', Mã đề thi: ' || :NEW.MADETHI || N', vào lúc: ' || :NEW.THOIGIAN_HOANTHANH);
END;

